### ISSUE TITLE
migrate problem (django.db.utils.OperationalError: table staff_member__new has no column named tags)

### ISSUE THREAD

**Issue by dieboldfr** [nadineproject/nadine#114]
Hello,

I would like to test Nadine. Where can I find a demo ?.

I tried to make an installation, but I have an issue when I call the migrate function.
python manage.py migrate

An idea ?
Thanks,
Thomas

(django.db.utils.OperationalError: table staff_member__new has no column named tags)

> Operations to perform:
  Synchronize unmigrated apps: taggit_templatetags, djcelery, jsignature, easy_pdf
  Apply all migrations: arpwatch, taggit, sessions, admin, sites, auth, interlink, contenttypes, members, staff
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying staff.0001_initial...Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 37, in database_forwards
    field,
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 176, in add_field
    self._remake_table(model, create_fields=[field])
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 144, in _remake_table
    self.quote_name(model._meta.db_table),
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 102, in execute
    cursor.execute(sql, params)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/thomas/nadine/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table staff_member__new has no column named tags

**Comment by jsayles** [comment]
Sorry @dieboldfr, you stumbled on an issue where the default settings didn't really work.  Thilo hit this same problem so I removed the SQLite example and made Postgres required.  Get your database setup and you'll work just fine.
