### ISSUE TITLE
Crontab:  Ending membership tasks not triggered

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#326]
Yesterday I ended member D.G.'s PT5 membership.
- 7/20 was the last day of the membership
- I set the membership to end on 7/20
- I did not start a new membership at that time (as of today, I started a new Advocate membership for D.G.)

Tasks for en expiring membership were not triggered.

**Comment by jsayles** [comment]
The following error was found in the logs and shows what is happening:

[23/Jul/2017 08:30:15] ERROR [django_crontab.crontab:147] Failed to complete cronjob at ('30 8 * * *', 'django.core.management.call_command', ['checkin_exiting'])
Traceback (most recent call last):
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/nadine/webapp/nadine/nadine/management/commands/checkin_exiting.py", line 19, in handle
    for membership in Membership.objects.filter(end_date=one_week_ago):
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1154, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1034, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1352, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'end_date' into field. Choices are: bill_day, id, individualmembership, oldmembership, organizationmembership, subscriptions
