### ISSUE TITLE
Crontab:  Process Mail Error Leaves Lock File

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#328]
The "process_mail" command failed with the following error and then the system was stuck and couldn't process any other mail because the lock file was left behind.  

[18/Jul/2017 22:24:04] ERROR [django_crontab.crontab:147] Failed to complete cronjob at ('*/2 * * * *', 'django.core.management.call_command', ['process_mail'])
Traceback (most recent call last):
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/home/nadine/webapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/nadine/webapp/nadine/interlink/management/commands/process_mail.py", line 19, in handle
    MailingList.objects.fetch_all_mail()
  File "/home/nadine/webapp/nadine/interlink/models.py", line 54, in fetch_all_mail
    ml.fetch_mail(logger)
  File "/home/nadine/webapp/nadine/interlink/models.py", line 94, in fetch_mail
    return checker.fetch_mail()
  File "/home/nadine/webapp/nadine/interlink/mail.py", line 20, in fetch_mail
    pop_client = poplib.POP3_SSL(self.mailing_list.pop_host, self.mailing_list.pop_port)
  File "/usr/lib/python2.7/poplib.py", line 346, in __init__
    for res in socket.getaddrinfo(self.host, self.port, 0, socket.SOCK_STREAM):
gaierror: [Errno -5] No address associated with hostname
[18/Jul/2017 22:28:04] WARNING [django_crontab.crontab:138] Tried to start cron job ('*/2 * * * *', 'django.core.management.call_command', ['process_mail']) that is already running.

**Comment by jsayles** [comment]
Errors have been happening off and on since this was opened and no lock files have ever been left behind.  Closing.
