### ISSUE TITLE
Error installing Nadine (Debian10/Django3.1/Python3.7.3)

### ISSUE THREAD

**Issue by goodjobjus** [nadineproject/nadine#453]
Hello all!
It's been what seems like a century that I've used my coding skills - and so I'm taking baby steps with this install.  However, have run into this issue right from the get go.

_**(nadine) root@li508-231:~/nadine# pip3 install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.tx_t'**_

Not sure where this issue has come from nor how important it is to the install as it's a txt file.  But then I continue to run into further issues:

_**(nadine) root@li508-231:~/nadine/nadine# ./manage.py setup
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/nadine/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 429, in execute_from_command_line
    utility.execute()
  File "/root/nadine/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/nadine/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/root/nadine/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 67, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/root/nadine/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/root/nadine/nadine/nadine/management/commands/setup.py", line 11, in <module>
    from django.core.management.utils import get_random_secret_key
ImportError: No module named utils**_

**Comment by jsayles** [comment]
The requirements file has been replaced and I have updated the docs to reflect the shift to using pipenv.  This is the step that installs all the libraries, like Django so it is very important.  That is why you are getting a Django error when you ran setup.

**Comment by hcortez-bit** [comment]
@jsayles Hello sorry, where can I find the documentation for the latest versions, I only found up to 2.1 but it doesn't work for these new ones

thanks
